- name: install MySQL-python (dependicies)
  yum:
    name: MySQL-python
    state: latest

- name: Create a new database with name 'zabbix_db'
  community.mysql.mysql_db:
    name: "{{DBName}}"
    state: present
    login_user: root
    login_password: 121212

- name: Create database user with name 'muhannad' and password '1212' with all database privileges
  community.mysql.mysql_user:
    login_user: root
    login_password: 121212
    name: "{{DBUser}}"
    password: "{{DBUserPsssword}}"
    priv: '*.*:ALL'
    state: present

- name: Reload privilege tables
  command: 'mysql -ne "{{ item }}" -u root -p121212'
  with_items:
    - FLUSH PRIVILEGES
