- name: include default step variables
  include_vars:
    file: myvars.yml

- name: install MySQL-python (dependicies)
  yum:
    name: MySQL-python
    state: latest

- name: see DBRootPassword
  debug:
    var: DBRootPassword

- name: Create a new database with name 'zabbix_db'
  community.mysql.mysql_db:
    name: "{{DBName}}"
    state: present
    login_user: root
    login_password: "{{DBRootPassword}}"

- name: Create database user with name 'muhannad' and password '1212' with all database privileges
  community.mysql.mysql_user:
    login_user: root
    login_password: "{{DBRootPassword}}"
    name: "{{DBUser}}"
    password: "{{DBUserPsssword}}"
    priv: '*.*:ALL'
    state: present

- name: Reload privilege tables
  command: 'mysql -ne "FLUSH PRIVILEGES" -u root -p{{DBRootPassword}}'
